// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airplane-api/pkg/models/shared"
	"net/http"
)

type CancelRunRequest struct {
	// CancelRunRequest
	Request shared.ApiextCancelRunRequest `request:"mediaType=application/json"`
}

type CancelRunResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
