// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/pkg/models/shared"
	"net/http"
)

type CancelPromptResponse struct {
	// OK
	CancelPromptResponse *shared.CancelPromptResponse
	ContentType          string
	StatusCode           int
	RawResponse          *http.Response
}

func (o *CancelPromptResponse) GetCancelPromptResponse() *shared.CancelPromptResponse {
	if o == nil {
		return nil
	}
	return o.CancelPromptResponse
}

func (o *CancelPromptResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelPromptResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelPromptResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
