// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/v2/pkg/models/shared"
	"net/http"
)

type CancelPromptResponse struct {
	// OK
	CancelPromptResponse *shared.CancelPromptResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CancelPromptResponse) GetCancelPromptResponse() *shared.CancelPromptResponse {
	if o == nil {
		return nil
	}
	return o.CancelPromptResponse
}

func (o *CancelPromptResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelPromptResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelPromptResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
