// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airplane-api/pkg/models/shared"
	"net/http"
)

type ExecuteRunbookQueryParams struct {
	// Environment to execute the runbook in.
	EnvSlug *string `queryParam:"style=form,explode=true,name=envSlug"`
}

type ExecuteRunbookRequest struct {
	QueryParams ExecuteRunbookQueryParams
	// ExecuteRunbookRequest
	Request shared.ApiextExecuteRunbookRequest `request:"mediaType=application/json"`
}

type ExecuteRunbookResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ApiextExecuteRunbookResponse *shared.ApiextExecuteRunbookResponse
}
