// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/pkg/models/shared"
	"net/http"
)

type ExecuteTaskRequest struct {
	// ExecuteTaskRequest
	ApiextExecuteTaskRequest shared.ApiextExecuteTaskRequest `request:"mediaType=application/json"`
	// Environment to execute the task in.
	EnvSlug *string `queryParam:"style=form,explode=true,name=envSlug"`
}

type ExecuteTaskResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ApiextExecuteTaskResponse *shared.ApiextExecuteTaskResponse
}
