// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/pkg/models/shared"
	"net/http"
)

type ExecuteRunbookRequest struct {
	// ExecuteRunbookRequest
	ExecuteRunbookRequest shared.ExecuteRunbookRequest `request:"mediaType=application/json"`
	// Environment to execute the runbook in.
	EnvSlug *string `queryParam:"style=form,explode=true,name=envSlug"`
}

func (o *ExecuteRunbookRequest) GetExecuteRunbookRequest() shared.ExecuteRunbookRequest {
	if o == nil {
		return shared.ExecuteRunbookRequest{}
	}
	return o.ExecuteRunbookRequest
}

func (o *ExecuteRunbookRequest) GetEnvSlug() *string {
	if o == nil {
		return nil
	}
	return o.EnvSlug
}

type ExecuteRunbookResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ExecuteRunbookResponse *shared.ExecuteRunbookResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ExecuteRunbookResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ExecuteRunbookResponse) GetExecuteRunbookResponse() *shared.ExecuteRunbookResponse {
	if o == nil {
		return nil
	}
	return o.ExecuteRunbookResponse
}

func (o *ExecuteRunbookResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ExecuteRunbookResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
