// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/pkg/models/shared"
	"net/http"
)

type ExecuteRunbookRequest struct {
	// ExecuteRunbookRequest
	ExecuteRunbookRequest shared.ExecuteRunbookRequest `request:"mediaType=application/json"`
	// Environment to execute the runbook in.
	EnvSlug *string `queryParam:"style=form,explode=true,name=envSlug"`
}

type ExecuteRunbookResponse struct {
	ContentType string
	// OK
	ExecuteRunbookResponse *shared.ExecuteRunbookResponse
	StatusCode             int
	RawResponse            *http.Response
}
