// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/v2/pkg/models/shared"
	"net/http"
)

type GetPromptRequest struct {
	// ID of the prompt to retrieve.
	ID string `queryParam:"style=form,explode=true,name=id"`
}

func (o *GetPromptRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetPromptResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GetPromptResponse *shared.GetPromptResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetPromptResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPromptResponse) GetGetPromptResponse() *shared.GetPromptResponse {
	if o == nil {
		return nil
	}
	return o.GetPromptResponse
}

func (o *GetPromptResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPromptResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
