// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/v2/pkg/models/shared"
	"net/http"
)

type GetRunRequest struct {
	// ID of the run to retrieve.
	ID string `queryParam:"style=form,explode=true,name=id"`
}

func (o *GetRunRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetRunResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GetRunResponse *shared.GetRunResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetRunResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRunResponse) GetGetRunResponse() *shared.GetRunResponse {
	if o == nil {
		return nil
	}
	return o.GetRunResponse
}

func (o *GetRunResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRunResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
