// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airplane-api/pkg/models/shared"
	"net/http"
)

type GetSessionQueryParams struct {
	// ID of the session to retrieve.
	ID string `queryParam:"style=form,explode=true,name=id"`
}

type GetSessionRequest struct {
	QueryParams GetSessionQueryParams
}

type GetSessionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ApiextGetSessionResponse *shared.ApiextGetSessionResponse
}
