// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/pkg/models/shared"
	"net/http"
)

type GetSessionRequest struct {
	// ID of the session to retrieve.
	ID string `queryParam:"style=form,explode=true,name=id"`
}

type GetSessionResponse struct {
	ContentType string
	// OK
	GetSessionResponse *shared.GetSessionResponse
	StatusCode         int
	RawResponse        *http.Response
}
