// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/airplane-go-sdk/v3/pkg/models/shared"
	"net/http"
)

type ListSessionsRequest struct {
	// Number of results per call. Accepted values: 0 - 50. The default: 50.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The offset used for this page of results.
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
	// Only fetch sessions for this specific runbook.
	RunbookID *string `queryParam:"style=form,explode=true,name=runbookID"`
	// Fetch sessions last updated after this time (RFC 3339 format).
	UpdatedAfter *string `queryParam:"style=form,explode=true,name=updatedAfter"`
	// Fetch sessions last updated before this time (RFC 3339 format).
	UpdatedBefore *string `queryParam:"style=form,explode=true,name=updatedBefore"`
}

func (o *ListSessionsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListSessionsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListSessionsRequest) GetRunbookID() *string {
	if o == nil {
		return nil
	}
	return o.RunbookID
}

func (o *ListSessionsRequest) GetUpdatedAfter() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAfter
}

func (o *ListSessionsRequest) GetUpdatedBefore() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedBefore
}

type ListSessionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ListSessionResponse *shared.ListSessionResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListSessionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListSessionsResponse) GetListSessionResponse() *shared.ListSessionResponse {
	if o == nil {
		return nil
	}
	return o.ListSessionResponse
}

func (o *ListSessionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListSessionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
