// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airplane-api/pkg/models/shared"
	"net/http"
)

type ListRunsRequest struct {
	// Number of results per call. Accepted values: 0 - 50. Default: 50.
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// The offset used for this page of results.
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
	// Fetch runs last updated after this time (RFC 3339 format).
	Since *string `queryParam:"style=form,explode=true,name=since"`
	// Unique ID of the task to fetch runs for.
	TaskID *string `queryParam:"style=form,explode=true,name=taskID"`
	// Unique slug of the task to fetch runs for.
	TaskSlug *string `queryParam:"style=form,explode=true,name=taskSlug"`
	// Fetch runs last updated before this time (RFC 3339 format).
	Until *string `queryParam:"style=form,explode=true,name=until"`
}

type ListRunsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ApiextListRunsResponse *shared.ApiextListRunsResponse
}
