// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airplane-api/pkg/models/shared"
	"net/http"
)

type SubmitPromptRequest struct {
	// SubmitPromptRequest
	Request shared.ApiextSubmitPromptRequest `request:"mediaType=application/json"`
}

type SubmitPromptResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ApiextSubmitPromptResponse *shared.ApiextSubmitPromptResponse
}
