// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AgentLabel struct {
	// Agent label key.
	Key *string `json:"key,omitempty"`
	// Agent label value.
	Value *string `json:"value,omitempty"`
}

func (o *AgentLabel) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *AgentLabel) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
