// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextCancelPromptRequest - CancelPromptRequest
type ApiextCancelPromptRequest struct {
	// Unique ID of the prompt.
	ID *string `json:"id,omitempty"`
}
