// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextExecuteRunbookResponse - OK
type ApiextExecuteRunbookResponse struct {
	// Unique ID of the runbook's session.
	SessionID *string `json:"sessionID,omitempty"`
}
