// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextCancelPromptResponse - OK
type ApiextCancelPromptResponse struct {
	// Unique ID of the prompt.
	ID *string `json:"id,omitempty"`
}
