// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextListRunsResponse - OK
type ApiextListRunsResponse struct {
	// Retrieved runs.
	Runs []ApiextGetRunResponse `json:"runs,omitempty"`
}
