// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextListPromptsResponse - OK
type ApiextListPromptsResponse struct {
	// Retrieved prompts.
	Prompts []PromptsifacePrompt `json:"prompts,omitempty"`
}
