// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ApiextConstraints struct {
	// Determines whether this parameter must be set.
	Optional *bool `json:"optional,omitempty"`
	// Valid values for a given parameter.
	Options interface{} `json:"options,omitempty"`
	// Regular expression used to determine if a parameter is valid.
	Regex *string `json:"regex,omitempty"`
}
