// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ApiextAgentLabel struct {
	// Agent label key.
	Key *string `json:"key,omitempty"`
	// Agent label value.
	Value *string `json:"value,omitempty"`
}
