// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextCancelRunRequest - CancelRunRequest
type ApiextCancelRunRequest struct {
	// Unique ID of the run to cancel.
	RunID *string `json:"runID,omitempty"`
}
