// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextExecuteTaskRequest - ExecuteTaskRequest
type ApiextExecuteTaskRequest struct {
	// Unique ID of the task. You can find your task's ID by visiting the task's page on Airplane.
	// The task ID is located at the end of the url.
	//
	// e.g. the task ID for `https://app.airplane.dev/tasks/tsk20210728zxb2vxn` is `tsk20210728zxb2vxn`
	//
	// Either an ID or a slug must be provided.
	ID *string `json:"id,omitempty"`
	// Mapping of parameter slug to value. You can find your task's parameter slugs inside the
	// task editor on Airplane or by running `airplane tasks list` from the CLI.
	ParamValues map[string]string `json:"paramValues,omitempty"`
	Resources   map[string]string `json:"resources,omitempty"`
	// Unique slug of the task. You can find your task's slug next to the task's name within the
	// task editor on Airplane or by running `airplane tasks list` from the CLI.
	//
	// Either an ID or a slug must be provided.
	Slug *string `json:"slug,omitempty"`
}
