// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextListSessionResponse - OK
type ApiextListSessionResponse struct {
	// Retrieved sessions.
	Sessions []ApiextGetSessionResponse `json:"sessions,omitempty"`
}
