// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextGetPromptResponse - OK
type ApiextGetPromptResponse struct {
	Prompt *PromptsifacePrompt `json:"prompt,omitempty"`
}
