// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ApiextGetOutputsResponse - OK
type ApiextGetOutputsResponse struct {
	// Outputs from this run.
	Output map[string]string `json:"output,omitempty"`
}
