// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ApiextRunConstraints struct {
	// Agent run constraints. Used to control which agents a run can be scheduled on.
	Labels []ApiextAgentLabel `json:"labels,omitempty"`
}
