// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CancelPromptRequest - CancelPromptRequest
type CancelPromptRequest struct {
	// Unique ID of the prompt.
	ID *string `json:"id,omitempty"`
}
