// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ExecuteTaskResponse - OK
type ExecuteTaskResponse struct {
	// Unique ID of the task execution's run.
	RunID *string `json:"runID,omitempty"`
}
