// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GetOutputsResponse struct {
	// Outputs from this run.
	Output map[string]string `json:"output,omitempty"`
}

func (o *GetOutputsResponse) GetOutput() map[string]string {
	if o == nil {
		return nil
	}
	return o.Output
}
