// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetPromptResponse - OK
type GetPromptResponse struct {
	Prompt *PromptsifacePrompt `json:"prompt,omitempty"`
}
