// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// GetSessionResponseStatusEnum - Status of this session.
type GetSessionResponseStatusEnum string

const (
	GetSessionResponseStatusEnumPending    GetSessionResponseStatusEnum = "Pending"
	GetSessionResponseStatusEnumActive     GetSessionResponseStatusEnum = "Active"
	GetSessionResponseStatusEnumWaiting    GetSessionResponseStatusEnum = "Waiting"
	GetSessionResponseStatusEnumSucceeded  GetSessionResponseStatusEnum = "Succeeded"
	GetSessionResponseStatusEnumFailed     GetSessionResponseStatusEnum = "Failed"
	GetSessionResponseStatusEnumCancelling GetSessionResponseStatusEnum = "Cancelling"
	GetSessionResponseStatusEnumCancelled  GetSessionResponseStatusEnum = "Cancelled"
)

func (e *GetSessionResponseStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "Pending":
		fallthrough
	case "Active":
		fallthrough
	case "Waiting":
		fallthrough
	case "Succeeded":
		fallthrough
	case "Failed":
		fallthrough
	case "Cancelling":
		fallthrough
	case "Cancelled":
		*e = GetSessionResponseStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSessionResponseStatusEnum: %s", s)
	}
}

// GetSessionResponse - OK
type GetSessionResponse struct {
	// When this session was created.
	CreatedAt *string `json:"createdAt,omitempty"`
	// ID of the user that created this session.
	CreatedBy *string `json:"createdBy,omitempty"`
	// Unique ID of this session.
	ID *string `json:"id,omitempty"`
	// Whether or not the session is private.
	IsPrivate *bool `json:"isPrivate,omitempty"`
	// Name of this session.
	Name *string `json:"name,omitempty"`
	// Mapping of parameter slug to value used in this session's execution.
	ParamValues map[string]string `json:"paramValues,omitempty"`
	// Schema for the set of values users can provide when executing this session.
	Params []Parameter `json:"params,omitempty"`
	// Explicit permissions of this session if it is private.
	Permissions []Permission `json:"permissions,omitempty"`
	// ID of the runbook this session was spawned from if triggered from a runbook.
	RunbookID *string `json:"runbookID,omitempty"`
	// Status of this session.
	Status *GetSessionResponseStatusEnum `json:"status,omitempty"`
	// ID of the team that owns this session.
	TeamID *string `json:"teamID,omitempty"`
	// When this session was updated.
	UpdatedAt *string `json:"updatedAt,omitempty"`
	// ID of the user who updated this session.
	UpdatedBy *string `json:"updatedBy,omitempty"`
}
