// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListPromptsResponse - OK
type ListPromptsResponse struct {
	// Retrieved prompts.
	Prompts []PromptsifacePrompt `json:"prompts,omitempty"`
}

func (o *ListPromptsResponse) GetPrompts() []PromptsifacePrompt {
	if o == nil {
		return nil
	}
	return o.Prompts
}
