// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListRunsResponse struct {
	// Retrieved runs.
	Runs []GetRunResponse `json:"runs,omitempty"`
}

func (o *ListRunsResponse) GetRuns() []GetRunResponse {
	if o == nil {
		return nil
	}
	return o.Runs
}
