// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListSessionResponse - OK
type ListSessionResponse struct {
	// Retrieved sessions.
	Sessions []GetSessionResponse `json:"sessions,omitempty"`
}
