// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListSessionResponse struct {
	// Retrieved sessions.
	Sessions []GetSessionResponse `json:"sessions,omitempty"`
}

func (o *ListSessionResponse) GetSessions() []GetSessionResponse {
	if o == nil {
		return nil
	}
	return o.Sessions
}
