// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ParametersParameters struct {
	Parameters []ParametersParameter `json:"parameters,omitempty"`
}

func (o *ParametersParameters) GetParameters() []ParametersParameter {
	if o == nil {
		return nil
	}
	return o.Parameters
}
