// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PromptsifacePrompt struct {
	// Custom prompt cancellation text.
	CancelText *string `json:"cancelText,omitempty"`
	// When this prompt was cancelled. This value will be null if the prompt has not been cancelled.
	CancelledAt *string `json:"cancelledAt,omitempty"`
	// Who cancelled this this prompt. This value will be null if the prompt has not been cancelled.
	CancelledBy *string `json:"cancelledBy,omitempty"`
	// Custom prompt confirmation text.
	ConfirmText *string `json:"confirmText,omitempty"`
	// When this prompt was created.
	CreatedAt *string `json:"createdAt,omitempty"`
	// Prompt description. Supports markdown.
	Description *string `json:"description,omitempty"`
	// Unique ID of the prompt.
	ID        *string                `json:"id,omitempty"`
	Reviewers *PromptsifaceReviewers `json:"reviewers,omitempty"`
	// Unique ID of the run the prompt belongs to.
	RunID  *string               `json:"runID,omitempty"`
	Schema *ParametersParameters `json:"schema,omitempty"`
	// When this prompt was submitted. This value will be null if the prompt has not been submitted.
	SubmittedAt *string `json:"submittedAt,omitempty"`
	// Who submitted this this prompt. This value will be null if the prompt has not been submitted.
	SubmittedBy *string `json:"submittedBy,omitempty"`
	// Mapping of parameter slug to value submitted to this prompt.
	Values map[string]string `json:"values,omitempty"`
}
