// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SubmitPromptResponse - OK
type SubmitPromptResponse struct {
	// Unique ID of the prompt.
	ID *string `json:"id,omitempty"`
}
